name: Auto Commit for PR Badge

on:
  schedule:
    - cron: '*/0.5 * * * *'  # Runs every 30 minutes
  workflow_dispatch:  # Allows manual execution

jobs:
  auto-commit:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
        with:
          token: ${{ secrets.GITHUB_TOKEN }}

      - name: Configure Git
        run: |
          git config --global user.name "github-actions[bot]"
          git config --global user.email "github-actions[bot]@users.noreply.github.com"

      - name: Ensure Repo is Up-to-Date
        run: git pull origin main

      - name: Detect Changes or Modify a File
        run: |
          if [[ -z $(git status --porcelain) ]]; then
            echo "No changes detected. Updating timestamp."
            echo "Last update: $(date)" > last_update.log
            git add last_update.log
          else
            echo "Changes detected. Proceeding with commit."
            git add .
          fi

      - name: Commit and Push Changes
        run: |
          git commit -m "Automated commit for PR Badge update [$(date)]"
          git push origin main
